version: '3.4'

services:
    php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./app/:/var/www/app/:delegated
        networks:
            - app
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./app/:/var/www/app/:delegated
        ports:
            - ${NGINX_EXPOSE_PORT}:80
        networks:
            - app
networks:
    app:
