alias c="clear"
alias h="history"
alias bslist="brew services list"
alias bsstop="brew services stop"
alias bsstart="brew services start"
alias bsrestart="brew services restart"
alias sdown="sudo shutdown -h now" 

#Symfony
alias sc="php bin/console"
alias scaw=" php bin/console debug:autowiring"
alias scawa=" php bin/console debug:autowiring --all"
alias scdr=" php bin/console debug:route"
alias sst="symfony server:start"
alias scmke="php bin/console make:entity" 
alias scmkmg="php bin/console make:migration"
alias scdmm="php bin/console doctrine:migrations:migrate" 
alias scmkct="php bin/console make:controller" 
alias scmkcr="php bin/console make:crud" 
alias scmkfr="php bin/console make:form" 
alias sccc="php bin/console cache:clear" 
