version: '3.4'

services:
  website:
    container_name: ${PROJECT_NAME}_apache
    build: ./docker/apache/
    volumes:
      - ./app:/var/www/html
      - ./docker/config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/.bashrc:/root/.bashrc
    ports:
      - 8006:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - symfony
  database:
    container_name: ${PROJECT_NAME}_postgres
    restart: always
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - symfony
networks:
  symfony:
