version: '3.4'

services:
  website:
    container_name: ${PROJECT_NAME}_apache
    build: ./docker/apache/
    volumes:
      - ./app:/var/www/html
    ports:
      - ${APACHE_EXPOSE_PORT}:80
    networks:
      - apachepostgresql
  database:
    container_name: postgresql
    restart: always
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    networks:
      - apachepostgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data

networks:
  apachepostgresql: