version: '3.4'

services:
    php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./app/:/var/www/app/:delegated
        networks:
            - app
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./app/:/var/www/app/:delegated
        ports:
            - ${NGINX_EXPOSE_PORT}:80
        networks:
            - app
    database:
        container_name: postgresql
#        restart: always
        image: postgres:${POSTGRES_VERSION}
        ports:
            - ${POSTGRES_EXPOSED_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./database:/var/lib/postgresql/data
        networks:
            - app


networks:
    app:
