version: '3.4'

services:
    php:
        container_name: ${PROJECT_NAME}_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./app/:/var/www/app/:delegated
        networks:
            - app
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./app/:/var/www/app/:delegated
        ports:
            - ${NGINX_EXPOSE_PORT}:80
        networks:
            - app
    database:
        container_name: mysql
        restart: always
        image: mysql:${MYSQL_VERSION}
        command: [ "--default-authentication-plugin=mysql_native_password" ]
        ports:
            - ${MYSQL_EXPOSRED_PORT}:3306
        networks:
            - app
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./database:/var/lib/mysql

networks:
    app:
