version: '3.4'

services:
  database:
    container_name: postgresql
    restart: always
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
